// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL7jCPh2p2zEXEwTB7p4dJtUiwwsN3Iq8',
    appId: '1:502418497658:web:b87dcee5c8dd4dbfc59bc3',
    messagingSenderId: '502418497658',
    projectId: 'family-calendar-65220',
    authDomain: 'family-calendar-65220.firebaseapp.com',
    storageBucket: 'family-calendar-65220.firebasestorage.app',
    measurementId: 'G-N19DXNNP2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3LQbbMZLhwTjmTowYqSlcw3eQntj4zs0',
    appId: '1:502418497658:android:0b4a3be915f1e9b9c59bc3',
    messagingSenderId: '502418497658',
    projectId: 'family-calendar-65220',
    storageBucket: 'family-calendar-65220.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoTc8DgCHpSd_0vjkfzNOS6afZ4VY5NMM',
    appId: '1:502418497658:ios:1e1c1d3995ba9960c59bc3',
    messagingSenderId: '502418497658',
    projectId: 'family-calendar-65220',
    storageBucket: 'family-calendar-65220.firebasestorage.app',
    iosBundleId: 'com.example.calendar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoTc8DgCHpSd_0vjkfzNOS6afZ4VY5NMM',
    appId: '1:502418497658:ios:1e1c1d3995ba9960c59bc3',
    messagingSenderId: '502418497658',
    projectId: 'family-calendar-65220',
    storageBucket: 'family-calendar-65220.firebasestorage.app',
    iosBundleId: 'com.example.calendar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCL7jCPh2p2zEXEwTB7p4dJtUiwwsN3Iq8',
    appId: '1:502418497658:web:0a424bff3beadf10c59bc3',
    messagingSenderId: '502418497658',
    projectId: 'family-calendar-65220',
    authDomain: 'family-calendar-65220.firebaseapp.com',
    storageBucket: 'family-calendar-65220.firebasestorage.app',
    measurementId: 'G-12J5K3VSQG',
  );
}
